%% ====== Thông số quadrotor =====
% Các hằng số vật lý
g  = 9.8;              % (m/s^2) gia tốc trọng trường
m  = 3.5;              % (kg) khối lượng quadrotor
l  = 0.2;              % (m) khoảng cách từ tâm đến mỗi rotor

% Hệ số khí động học
b  = 1.5e-5;           % (N*s^2) hệ số lực nâng
d  = 1.5e-7;           % (N*m*s^2) hệ số mô-men cản

% Mô-men quán tính
Ixx = 0.02;             % Jx (kg*m^2)
Iyy = 0.02;             % Jy (kg*m^2)
Izz = 0.03;             % Jz (kg*m^2)
Ir = 150e-7;           % JT(kg*m^2) mô-men tổng (nếu có dùng cho mô hình đầy đủ)

% Hệ số ma sát tuyến tính
kx = 0.01;             % (N*s/m)
ky = 0.01;             % (N*s/m)
kz = 0.01;             % (N*s/m)

% Hệ số ma sát góc (moment damping)
k_phi   = 0.1;         % (N*s/m)
k_theta = 0.1;         % (N*s/m)
k_psi   = 0.1;         % (N*s/m)

%% ==== Thông số bộ điều khiển  ====
Kp = 1; 
Ki = 0.01; 
Kd = 0.1;

%% Gom các tham số lại trong một struct (tiện cho mô phỏng)
params = struct( ...
    'g', g, ...
    'm', m, ...
    'l', l, ...
    'b', b, ...
    'd', d, ...
    'Ixx', Ixx, ...
    'Iyy', Iyy, ...
    'Izz', Izz, ...
    'Ir', Ir, ...
    'kx', kx, ...
    'ky', ky, ...
    'kz', kz, ...
    'k_phi', k_phi, ...
    'k_theta', k_theta, ...
    'k_psi', k_psi, ...
    'Kp', Kp, ...
    'Ki', Ki, ...
    'Kd', Kd ...
);

disp('Thông số quadrotor đã được khởi tạo:');
disp(params);
